src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EntrepriseRepository::class)
 */
class Entreprise
{
    /**
     * Id de l'entreprise
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * Enseigne de l'entreprise
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $enseigne;

    /**
     * Raison sociale de l'entreprise
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $raison_sociale;

    /////////////////////////////////////////////////

    /**
     * Numéro RIDET de l'entreprise
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $ridet;

    /**
     * Numéro CAFAT de l'entreprise
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $num_cafat;

    /**
     * Code NAF de l'entreprise
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $code_naf;

    /////////////////////////////////////////////////

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse_exec;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $cp_exec;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $commune_exec;

    /**
     * Adresse physique du siège de l'entreprise
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $adresse_siege;

    /**
     * Code postal du siège de l'entreprise
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $cp_siege;

    /**
     * Commune du siège de l'entreprise
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $commune_siege;

    /////////////////////////////////////////////////

    /**
     * Numéro de téléphone de contact de l'entreprise
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $telephone;

    /**
     * Email de contact de l'entreprise
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $email;

    /////////////////////////////////////////////////

    /**
     * Convention collective de l'entreprise
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $convention_collective;

    /**
     * Statut juridique  de l'entreprise
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $statut;

    /**
     * Nombre de salariés dans l'entreprise
     * @ORM\Column(type="integer", nullable=false)
     */
    private $nb_salaries;

    /**
     * @ORM\ManyToMany(targetEntity=Etudiant::class, mappedBy="entreprises")
     */
    private $etudiants;

    /**
     * @ORM\ManyToMany(targetEntity=Tuteur::class, mappedBy="entreprises")
     */
    private $tuteurs;

    public function __construct()
    {
        $this->etudiants = new ArrayCollection();
        $this->tuteurs = new ArrayCollection();
    }

    /////////////////////////////////////////////////
    //              GETTERS & SETTERS              //
    /////////////////////////////////////////////////

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEnseigne(): ?string
    {
        return $this->enseigne;
    }
    public function setEnseigne(string $enseigne): self
    {
        $this->enseigne = $enseigne;
        return $this;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raison_sociale;
    }
    public function setRaisonSociale(string $raison_sociale): self
    {
        $this->raison_sociale = $raison_sociale;
        return $this;
    }

    public function getRidet(): ?string
    {
        return $this->ridet;
    }
    public function setRidet(string $ridet): self
    {
        $this->ridet = $ridet;
        return $this;
    }

    public function getNumCafat(): ?string
    {
        return $this->num_cafat;
    }
    public function setNumCafat(string $num_cafat): self
    {
        $this->num_cafat = $num_cafat;
        return $this;
    }

    public function getCodeNaf(): ?string
    {
        return $this->code_naf;
    }
    public function setCodeNaf(string $code_naf): self
    {
        $this->code_naf = $code_naf;
        return $this;
    }

    public function getAdresseExec(): ?string
    {
        return $this->adresse_exec;
    }
    public function setAdresseExec(string $adresse_exec): self
    {
        $this->adresse_exec = $adresse_exec;
        return $this;
    }

    public function getCpExec(): ?string
    {
        return $this->cp_exec;
    }
    public function setCpExec(?string $cp_exec): self
    {
        $this->cp_exec = $cp_exec;
        return $this;
    }

    public function getCommuneExec(): ?string
    {
        return $this->commune_exec;
    }
    public function setCommuneExec(?string $commune_exec): self
    {
        $this->commune_exec = $commune_exec;
        return $this;
    }

    public function getAdresseSiege(): ?string
    {
        return $this->adresse_siege;
    }
    public function setAdresseSiege(string $adresse_siege): self
    {
        $this->adresse_siege = $adresse_siege;
        return $this;
    }

    public function getCpSiege(): ?string
    {
        return $this->cp_siege;
    }
    public function setCpSiege(string $cp_siege): self
    {
        $this->cp_siege = $cp_siege;
        return $this;
    }

    public function getCommuneSiege(): ?string
    {
        return $this->commune_siege;
    }
    public function setCommuneSiege(string $commune_siege): self
    {
        $this->commune_siege = $commune_siege;
        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }
    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;
        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }
    public function setEmail(string $email): self
    {
        $this->email = $email;
        return $this;
    }

    public function getConventionCollective(): ?string
    {
        return $this->convention_collective;
    }
    public function setConventionCollective(string $convention_collective): self
    {
        $this->convention_collective = $convention_collective;
        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }
    public function setStatut(string $statut): self
    {
        $this->statut = $statut;
        return $this;
    }

    public function getNbSalaries(): ?int
    {
        return $this->nb_salaries;
    }
    public function setNbSalaries(int $nb_salaries): self
    {
        $this->nb_salaries = $nb_salaries;
        return $this;
    }

    /**
     * @return Collection|Etudiant[]
     */
    public function getEtudiants(): Collection
    {
        return $this->etudiants;
    }

    public function addEtudiant(Etudiant $etudiant): self
    {
        if (!$this->etudiants->contains($etudiant)) {
            $this->etudiants[] = $etudiant;
            $etudiant->addEntreprise($this);
        }

        return $this;
    }

    public function removeEtudiant(Etudiant $etudiant): self
    {
        if ($this->etudiants->contains($etudiant)) {
            $this->etudiants->removeElement($etudiant);
            $etudiant->removeEntreprise($this);
        }
        return $this;
    }

    /**
     * @return Collection|Tuteur[]
     */
    public function getTuteurs(): Collection
    {
        return $this->tuteurs;
    }

    public function addTuteur(Tuteur $tuteur): self
    {
        if (!$this->tuteurs->contains($tuteur)) {
            $this->tuteurs[] = $tuteur;
            $tuteur->addEntreprise($this);
        }

        return $this;
    }

    public function removeTuteur(Tuteur $tuteur): self
    {
        if ($this->tuteurs->contains($tuteur)) {
            $this->tuteurs->removeElement($tuteur);
            $tuteur->removeEntreprise($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getEnseigne();
    }
}

src/Form/EntrepriseType.php
<?php

namespace App\Form;

use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EntrepriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('enseigne')
            ->add('raison_sociale')
            ->add('ridet')
            ->add('num_cafat')
            ->add('code_naf')
            ->add('adresse_exec')
            ->add('cp_exec')
            ->add('commune_exec')
            ->add('adresse_siege')
            ->add('cp_siege')
            ->add('commune_siege')
            ->add('telephone')
            ->add('email')
            ->add('convention_collective')
            ->add('statut')
            ->add('nb_salaries')
            ->add('etudiants')
            ->add('tuteurs')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Entreprise::class,
        ]);
    }
}

src/Controller/EntrepriseController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Form\EntrepriseType;
use App\Repository\EntrepriseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/entreprise")
 */
class EntrepriseController extends AbstractController
{
    /**
     * @Route("/", name="entreprise_index", methods={"GET"})
     */
    public function index(EntrepriseRepository $entrepriseRepository): Response
    {
        return $this->render('entreprise/index.html.twig', [
            'entreprises' => $entrepriseRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="entreprise_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $entreprise = new Entreprise();
        $form = $this->createForm(EntrepriseType::class, $entreprise, [
            'action' => $this->generateUrl('entreprise_new')
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($entreprise);
            $entityManager->flush();
            $this->addFlash('success', 'Entreprise Ajoutée !');

            return $this->redirectToRoute('entreprise_index');
        }

        return $this->render('entreprise/new.html.twig', [
            'entreprise' => $entreprise,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="entreprise_show", methods={"GET"})
     */
    public function show(Entreprise $entreprise): Response
    {
        return $this->render('entreprise/show.html.twig', [
            'entreprise' => $entreprise,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="entreprise_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Entreprise $entreprise): Response
    {
        $form = $this->createForm(EntrepriseType::class, $entreprise, [
            'action' => $this->generateUrl('entreprise_edit', ['id' => $entreprise->getId()])
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', 'Entreprise Modifiée !');

            return $this->redirectToRoute('entreprise_index');
        }

        return $this->render('entreprise/edit.html.twig', [
            'entreprise' => $entreprise,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="entreprise_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Entreprise $entreprise): Response
    {
        if ($this->isCsrfTokenValid('delete'.$entreprise->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($entreprise);
            $entityManager->flush();
            $this->addFlash('success', 'Entreprise Supprimée !');
        }

        return $this->redirectToRoute('entreprise_index');
    }
}

templates/entreprise/_delete_form.html.twig
<form method="post" class="d-inline" action="{{ path('entreprise_delete', {'id': entreprise.id}) }}" onsubmit="return confirm('Confirmer la suppression de l'entreprise ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ entreprise.id) }}">
    <button class="btn btn-danger text-white">
        <i class="fas fa-trash-alt"></i>
    </button>
</form>

templates/entreprise/_form.html.twig
<br>
{{ form_start(form) }}

<div class="my-custom-class-for-errors"> {{ form_errors(form) }} </div>

<div class="col-10 mx-auto">

    <hr>

    <div class="row form-group">
        <div class="col-3">
            Enseigne
            {{ form_widget(form.enseigne, {'attr': {'class': 'form-control', 'placeholder' : "Enseigne"}}) }}
        </div>
        <div class="col-3">
            Raison sociale
            {{ form_widget(form.raison_sociale, {'attr': {'class': 'form-control', 'placeholder' : "Raison sociale"}}) }}
        </div>
        <div class="col-3">
            Téléphone
            {{ form_widget(form.telephone, {'attr': {'class': 'form-control', 'placeholder' : "Téléphone"}}) }}
        </div>
        <div class="col-3">
            Email
            {{ form_widget(form.email, {'attr': {'class': 'form-control', 'placeholder' : "Email"}}) }}
        </div>
    </div>

    <hr>

    <div class="row form-group">
        <div class="col-4">
            Adresse du lieu d'exécution
            {{ form_widget(form.adresse_exec, {'attr': {'class': 'form-control', 'placeholder' : "Adresse du lieu d'exécution"}}) }}
        </div>
        <div class="col-4">
            Code postal du lieu d'exécution
            {{ form_widget(form.cp_exec, {'attr': {'class': 'form-control', 'placeholder' : "Code postal du lieu d'exécution"}}) }}
        </div>
        <div class="col-4">
            Commune du lieu d'exécution
            {{ form_widget(form.commune_exec, {'attr': {'class': 'form-control', 'placeholder' : "Commune du lieu d'exécution"}}) }}
        </div>
    </div>

    <div class="row form-group">
        <div class="col-4">
            Adresse du siège
            {{ form_widget(form.adresse_siege, {'attr': {'class': 'form-control', 'placeholder' : "Adresse du siège"}}) }}
        </div>
        <div class="col-4">
            Code postal du siège
            {{ form_widget(form.cp_siege, {'attr': {'class': 'form-control', 'placeholder' : "Code postal du siège"}}) }}
        </div>
        <div class="col-4">
            Commune du siège
            {{ form_widget(form.commune_siege, {'attr': {'class': 'form-control', 'placeholder' : "Commune du siège"}}) }}
        </div>
    </div>

    <hr>

    <div class="row form-group">
        <div class="col-4">
            N° RIDET
            {{ form_widget(form.ridet, {'attr': {'class': 'form-control', 'placeholder' : "N° RIDET"}}) }}
        </div>
        <div class="col-4">
            N° CAFAT
            {{ form_widget(form.num_cafat, {'attr': {'class': 'form-control', 'placeholder' : "N° CAFAT"}}) }}
        </div>
        <div class="col-4">
            CODE NAF
            {{ form_widget(form.code_naf, {'attr': {'class': 'form-control', 'placeholder' : "CODE NAF"}}) }}
        </div>
    </div>

    <div class="row form-group">
        <div class="col-4">
            Convention collective
            {{ form_widget(form.convention_collective, {'attr': {'class': 'form-control', 'placeholder' : "Convention collective"}}) }}
        </div>
        <div class="col-4">
            Statut juridique
            {{ form_widget(form.statut, {'attr': {'class': 'form-control', 'placeholder' : "Statut juridique"}}) }}
        </div>
        <div class="col-4">
            Nombre de salariés
            {{ form_widget(form.nb_salaries, {'attr': {'class': 'form-control', 'placeholder' : "Nombre de salariés"}}) }}
        </div>
    </div>

    <hr>

    <div class="row form-group">
        <div class="col-6">
            Étudiant(s)
            {{ form_widget(form.etudiants, {'attr': {'class': 'form-control', 'placeholder' : "Étudiants"}}) }}
        </div>
        <div class="col-6">
            Tuteur(s)
            {{ form_widget(form.tuteurs, {'attr': {'class': 'form-control', 'placeholder' : "Tuteurs"}}) }}
        </div>
    </div>

    <hr>
    <div class="d-flex justify-content-center">
        <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
    </div>

{{ form_end(form) }}

templates/entreprise/edit.html.twig
{% block body %}
    <h1>Modifier l'entreprise</h1>
    {{ include('entreprise/_form.html.twig', {'button_label': 'Update'}) }}
{% endblock %}

templates/entreprise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Entreprise index{% endblock %}

{% block body %}
    <h1>Entreprises</h1>

    <button id="ajouter" data-target="#formModal" data-toggle="modal" class="btn btn-success" onclick="OpenModal('{{ path('entreprise_new') }}')">
        <i class="fas fa-plus"></i>
    </button>

    <br><br>

    <table id="datatable-example" class="table dt-responsive custom-table nowrap">
        <thead>
            <tr>
                <th>Enseigne</th>
                <th>Telephone</th>
                <th>Email</th>
                <th>Adresse</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for entreprise in entreprises %}
            <tr>
                <td>{{ entreprise.enseigne }}</td>
                <td>{{ entreprise.telephone }}</td>
                <td>{{ entreprise.email }}</td>
                <td>{{ entreprise.adresseExec ~ ', ' ~ entreprise.cpExec ~ ' ' ~ entreprise.communeExec | upper }}</td>
                <td>
                    <button data-target="#formModal" data-toggle="modal" class="btn btn-warning text-white" onclick="OpenModal('{{path('entreprise_show', {'id': entreprise.id})}}')">
                        <i class="fas fa-eye"></i>
                    </button>
                    <button data-target="#formModal" data-toggle="modal" class="btn btn-primary " onclick="OpenModal('{{path('entreprise_edit', {'id': entreprise.id})}}')">
                        <i class="fas fa-edit"></i>
                    </button>
                    {{ include('entreprise/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="18">aucune données</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/entreprise/new.html.twig
{% block body %}
    <h1>Créer une entreprise</h1>
    {{ include('entreprise/_form.html.twig') }}
{% endblock %}

templates/entreprise/show.html.twig
{% block body %}

<div class="col-10 mx-auto">

    <table class="table table-striped">
        <thead>
            <tr>
                <th colspan="5"><h2>Entreprise</h2></th>
            </tr>
        <thead>
        <tbody>
            <tr>
                <th>ID</th>
                <td>{{ entreprise.id }}</td>
                <td class="px-5">-</td>
                <th>Enseigne</th>
                <td>{{ entreprise.enseigne }}</td>
            </tr>
            <tr>
                <th>Raison sociale</th>
                <td>{{ entreprise.raisonSociale }}</td>
                <td class="px-5">-</td>
                <th>N° RIDET</th>
                <td>{{ entreprise.ridet }}</td>
            </tr>
            <tr>
                <th>N° CAFAT</th>
                <td>{{ entreprise.numCafat }}</td>
                <td class="px-5">-</td>
                <th>Code_naf</th>
                <td>{{ entreprise.codeNaf }}</td>
            </tr>
            <tr>
                <th>Adresse du lieu d'exécution</th>
                <td>{{ entreprise.adresseExec }}</td>
                <td class="px-5">-</td>
                <th>Code postal du lieu d'exécution</th>
                <td>{{ entreprise.cpExec }}</td>
            </tr>
            <tr>
                <th>Commune du lieu d'exécution</th>
                <td>{{ entreprise.communeExec }}</td>
                <td class="px-5">-</td>
                <th>Adresse du siège</th>
                <td>{{ entreprise.adresseSiege }}</td>
            </tr>
            <tr>
                <th>Code postal du siège</th>
                <td>{{ entreprise.cpSiege }}</td>
                <td class="px-5">-</td>
                <th>Commune du siège</th>
                <td>{{ entreprise.communeSiege }}</td>
            </tr>
            <tr>
                <th>Télephone</th>
                <td>{{ entreprise.telephone }}</td>
                <td class="px-5">-</td>
                <th>Email</th>
                <td>{{ entreprise.email }}</td>
            </tr>
            <tr>
                <th>Convention collective</th>
                <td>{{ entreprise.conventionCollective }}</td>
                <td class="px-5">-</td>
                <th>Statut juridique</th>
                <td>{{ entreprise.statut }}</td>
            </tr>
            <tr>
                <th>Nombre de salariés</th>
                <td>{{ entreprise.nbSalaries }}</td>
                <td class="px-5"></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>

</div><br>

{% endblock %}