src/Entity/Tuteur.php
<?php

namespace App\Entity;

use App\Repository\TuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TuteurRepository::class)
 */
class Tuteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fonction_occupe;

    /**
     * @ORM\Column(type="integer")
     */
    private $annee_experience;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $diplome_obtenu;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $diplome_max;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_habilitation;

    /**
     * @ORM\Column(type="date")
     */
    private $date_diplome;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_envoi_email_tutorat;

    /**
     * @ORM\ManyToMany(targetEntity=Entreprise::class, inversedBy="tuteurs")
     */
    private $entreprises;

    /**
     * @ORM\ManyToMany(targetEntity=Etudiant::class, inversedBy="tuteurs")
     */
    private $etudiants;

    public function __construct()
    {
        $this->entreprises = new ArrayCollection();
        $this->etudiants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getFonctionOccupe(): ?string
    {
        return $this->fonction_occupe;
    }

    public function setFonctionOccupe(string $fonction_occupe): self
    {
        $this->fonction_occupe = $fonction_occupe;

        return $this;
    }

    public function getAnneeExperience(): ?int
    {
        return $this->annee_experience;
    }

    public function setAnneeExperience(int $annee_experience): self
    {
        $this->annee_experience = $annee_experience;

        return $this;
    }

    public function getDiplomeObtenu(): ?string
    {
        return $this->diplome_obtenu;
    }

    public function setDiplomeObtenu(string $diplome_obtenu): self
    {
        $this->diplome_obtenu = $diplome_obtenu;

        return $this;
    }

    public function getDiplomeMax(): ?string
    {
        return $this->diplome_max;
    }

    public function setDiplomeMax(string $diplome_max): self
    {
        $this->diplome_max = $diplome_max;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateHabilitation(): ?\DateTime
    {
        return $this->date_habilitation;
    }

    public function setDateHabilitation(?\DateTime $date_habilitation): self
    {
        $this->date_habilitation = $date_habilitation;

        return $this;
    }

    public function getDateDiplome(): ?\DateTime
    {
        return $this->date_diplome;
    }

    public function setDateDiplome(\DateTime $date_diplome): self
    {
        $this->date_diplome = $date_diplome;

        return $this;
    }

    public function getDateEnvoiEmailTutorat(): ?\DateTime
    {
        return $this->date_envoi_email_tutorat;
    }

    public function setDateEnvoiEmailTutorat(?\DateTime $date_envoi_email_tutorat): self
    {
        $this->date_envoi_email_tutorat = $date_envoi_email_tutorat;

        return $this;
    }

    /**
     * @return Collection|Entreprise[]
     */
    public function getEntreprises(): Collection
    {
        return $this->entreprises;
    }

    public function addEntreprise(Entreprise $entreprise): self
    {
        if (!$this->entreprises->contains($entreprise)) {
            $this->entreprises[] = $entreprise;
        }

        return $this;
    }

    public function removeEntreprise(Entreprise $entreprise): self
    {
        if ($this->entreprises->contains($entreprise)) {
            $this->entreprises->removeElement($entreprise);
        }

        return $this;
    }

    /**
     * @return Collection|Etudiant[]
     */
    public function getEtudiants(): Collection
    {
        return $this->etudiants;
    }

    public function addEtudiant(Etudiant $etudiant): self
    {
        if (!$this->etudiants->contains($etudiant)) {
            $this->etudiants[] = $etudiant;
        }

        return $this;
    }

    public function removeEtudiant(Etudiant $etudiant): self
    {
        if ($this->etudiants->contains($etudiant)) {
            $this->etudiants->removeElement($etudiant);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNom() . " " . $this->getPrenom();
    }
}

src/Form/TuteurType.php
<?php

namespace App\Form;

use App\Entity\Tuteur;
use App\Entity\Entreprise;
use App\Entity\Etudiant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class TuteurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('fonction_occupe')
            ->add('annee_experience')
            ->add('diplome_obtenu')
            ->add('diplome_max')
            ->add('telephone')
            ->add('email')
            ->add('date_habilitation', BirthdayType::class, [
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'input'  => 'datetime',
            ])
            ->add('date_diplome', BirthdayType::class, [
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'input'  => 'datetime',
            ])
            ->add('date_envoi_email_tutorat', BirthdayType::class, [
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'input'  => 'datetime',
            ])
            ->add('entreprises', EntityType::class, [
                'class' => Entreprise::class,
                'choice_label' => 'enseigne',
                'multiple' => true,
            ])
            ->add('etudiants', EntityType::class, [
               'class' => Etudiant::class,
               'choice_label' => 'nom',
               'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tuteur::class,
        ]);
    }
}

src/Controller/TuteurController.php
<?php

namespace App\Controller;

use App\Entity\Tuteur;
use App\Form\TuteurType;
use App\Repository\TuteurRepository;

use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/tuteur")
 */
class TuteurController extends AbstractController
{
    /**
     * @Route("/", name="tuteur_index", methods={"GET"})
     */
    public function index(TuteurRepository $tuteurRepository, Request $request): Response
    {
        return $this->render('tuteur/index.html.twig', [
            'tuteurs' => $tuteurRepository->findAll()
        ]);
    }

    /**
     * @Route("/new", name="tuteur_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $tuteur = new Tuteur();
        $form = $this->createForm(TuteurType::class, $tuteur, [
            'action' => $this->generateUrl('tuteur_new')
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tuteur);
            $entityManager->flush();
            $this->addFlash('success', 'Tuteur Ajouté !');

            return $this->redirectToRoute('tuteur_index');
        }

        return $this->render('tuteur/new.html.twig', [
            'tuteur' => $tuteur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tuteur_show", methods={"GET"})
     */
    public function show(Tuteur $tuteur): Response
    {
        return $this->render('tuteur/show.html.twig', [
            'tuteur' => $tuteur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="tuteur_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Tuteur $tuteur): Response
    {
        $form = $this->createForm(TuteurType::class, $tuteur, [
            'action' => $this->generateUrl('tuteur_edit', ['id' => $tuteur->getId()]),
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', 'Tuteur Modifié !');

            return $this->redirectToRoute('tuteur_index');
        }

        return $this->render('tuteur/edit.html.twig', [
            'tuteur' => $tuteur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="tuteur_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Tuteur $tuteur): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tuteur->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($tuteur);
            $entityManager->flush();
            $this->addFlash('success', 'Tuteur Supprimé !');
        }

        return $this->redirectToRoute('tuteur_index');
    }
}

templates/tuteur/_delete_form.html.twig
<form method="post" class="d-inline" action="{{ path('tuteur_delete', {'id': tuteur.id}) }}" onsubmit="return confirm('Confirmer la suppression du tuteur ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tuteur.id) }}">
    <button class="btn btn-danger text-white">
        <i class="fas fa-trash-alt"></i>
    </button>
</form>

templates/tuteur/_form.html.twig
<br>
{{ form_start(form) }}

<div class="my-custom-class-for-errors"> {{ form_errors(form) }} </div>

<div class="col-10 mx-auto">

    <hr>

    <div class="row form-group">
        <div class="col-6">
            Prénom
            {{ form_widget(form.prenom, {'attr': {'class': 'form-control', 'placeholder' : "Prénom"}}) }}
        </div>
        <div class="col-6">
            Nom
            {{ form_widget(form.nom, {'attr': {'class': 'form-control', 'placeholder' : "Nom"}}) }}
        </div>
    </div>

    <div class="row form-group">
        <div class="col-6">
            Téléphone
            {{ form_widget(form.telephone, {'attr': {'class': 'form-control', 'placeholder' : "Téléphone"}}) }}
        </div>
        <div class="col-6">
            Email
            {{ form_widget(form.email, {'attr': {'class': 'form-control', 'placeholder' : "Email"}}) }}
        </div>
    </div>

    <hr>

    <div class="row form-group">
        <div class="col-8">
            Fonction occupée
            {{ form_widget(form.fonction_occupe, {'attr': {'class': 'form-control', 'placeholder' : "Fonction occupée"}}) }}
        </div>
        <div class="col-4">
            Années d'expérience
            {{ form_widget(form.annee_experience, {'attr': {'class': 'form-control', 'placeholder' : "Années d'expérience"}}) }}
        </div>
    </div>

    <hr>

    <div class="row form-group">
        <div class="col-5">
            Diplôme obtenu
            {{ form_widget(form.diplome_obtenu, {'attr': {'class': 'form-control', 'placeholder' : "Diplôme obtenu"}}) }}
        </div>
        <div class="col-5">
            Dernier diplôme
            {{ form_widget(form.diplome_max, {'attr': {'class': 'form-control', 'placeholder' : "Dernier diplôme"}}) }}
        </div>
        <div class="col-2">
            Date d'obtention du diplôme
            {{ form_widget(form.date_diplome, {'attr': {'class': 'form-control', 'placeholder' : "Date d'obtention du diplôme"}}) }}
        </div>
    </div>

    <hr>

    <div class="row form-group">
        <div class="col-6">
            Date d'habilitation
            {{ form_widget(form.date_habilitation, {'attr': {'class': 'form-control', 'placeholder' : "Date d'habilitation"}}) }}
        </div>
        <div class="col-6">
            Date d'envoi de l'email au tutorat
            {{ form_widget(form.date_envoi_email_tutorat, {'attr': {'class': 'form-control', 'placeholder' : "Date d'envoi du mail pour le tutorat"}}) }}
        </div>
    </div>

    <hr>

    <div class="row form-group">
        <div class="col-6">
            Entreprise(s)
            {{ form_widget(form.entreprises, {'attr': {'class': 'form-control', 'placeholder' : "Entreprise"}}) }}
        </div>
        <div class="col-6">
            Étudiant(s)
            {{ form_widget(form.etudiants, {'attr': {'class': 'form-control', 'placeholder' : "Étudiant"}}) }}
        </div>
    </div>

    <hr>

    <br>
    <div class="d-flex justify-content-center">
        <button class="btn btn-primary">
            {{ button_label|default('Enregistrer') }}
        </button>
    </div>

</div> <br>

{{ form_end(form) }}

templates/tuteur/edit.html.twig
{% block body %}
    <h1>Modification Tuteur</h1>
    {{ include('tuteur/_form.html.twig', {'button_label': 'Modifier','attr': {'class': 'btn btn-primary'}}) }}
{% endblock %}

templates/tuteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tuteurs{% endblock %}

{% block body %}

    <h1>Tuteurs</h1>

    <button id="ajouter" data-target="#formModal" data-toggle="modal" class="btn btn-success" onclick="OpenModal('{{ path('tuteur_new') }}')">
        <i class="fas fa-plus"></i>
    </button>

    <br><br>

    <table id="datatable-example" class="table dt-responsive custom-table nowrap">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Fonction_occupe</th>
                <th>Telephone</th>
                <th>Email</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
            {% for tuteur in tuteurs %}
                <tr>
                    <td>{{ tuteur.nom }}</td>
                    <td>{{ tuteur.prenom }}</td>
                    <td>{{ tuteur.fonctionOccupe }}</td>
                    <td>{{ tuteur.telephone }}</td>
                    <td>{{ tuteur.email }}</td>
                    <td>
                        <button data-target="#formModal" data-toggle="modal" class="btn btn-warning text-white" onclick="OpenModal('{{path('tuteur_show', {'id': tuteur.id})}}')">
                            <i class="fas fa-eye"></i>
                        </button>
                        <button data-target="#formModal" data-toggle="modal" class="btn btn-primary " onclick="OpenModal('{{path('tuteur_edit', {'id': tuteur.id})}}')">
                            <i class="fas fa-edit"></i>
                        </button>
                        {{ include('tuteur/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

</div>

{% endblock %}

templates/tuteur/new.html.twig
{% block body %}
    <h1>Créer un Nouveau Tuteur</h1>
    {{ include('tuteur/_form.html.twig') }}
{% endblock %}

templates/tuteur/show.html.twig
{% block body %}

<div class="col-8 mx-auto">

    <table class="table table-striped">
        <thead>
            <tr>
                <th colspan="2"><h2>Tuteur</h2></th>
            </tr>
        <thead>
        <tbody>
            <tr>
                <th>ID</th>
                <td>{{ tuteur.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ tuteur.nom }}</td>
            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ tuteur.prenom }}</td>
            </tr>
            <tr>
                <th>Fonction occupée</th>
                <td>{{ tuteur.fonctionOccupe }}</td>
            </tr>
            <tr>
                <th>Années d'experience</th>
                <td>{{ tuteur.anneeExperience }}</td>
            </tr>
            <tr>
                <th>Diplôme</th>
                <td>{{ tuteur.diplomeMax }}</td>
            </tr>
            <tr>
                <th>Télephone</th>
                <td>{{ tuteur.telephone }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ tuteur.email }}</td>
            </tr>
            <tr>
                <th>Date d'habilitation</th>
                <td>{{ tuteur.dateHabilitation ? tuteur.dateHabilitation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date d'obtention du diplôme</th>
                <td>{{ tuteur.dateDiplome ? tuteur.dateDiplome|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date d'envoi de l'email au tutorat</th>
                <td>{{ tuteur.dateEnvoiEmailTutorat ? tuteur.dateEnvoiEmailTutorat|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

</div><br>

{% endblock %}